name: Dev Pipeline - Test Integration

on:
  push:
    branches:
      - Dev

permissions:            # Add this section
  id-token: write        # Required for OIDC token generation
  contents: read         # Allows access to the repository contents

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev  # This specifies that the 'Dev' environment secrets will be used

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud with Workload Identity Federation
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/147961138027/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-pool"
          service_account: "github-ci-cd-dev@dev-env-441417.iam.gserviceaccount.com"

      - name: Set up gcloud CLI
        run: |
          echo "Configuring gcloud CLI"
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set compute/region europe-west4
          gcloud config set compute/zone europe-west4-a

      - name: Read and Create Resources
        run: |
          echo "Reading resources configuration"
          RESOURCES=$(jq -c '.resources[]' config/resources.json)

          for RESOURCE in $RESOURCES; do
            NAME=$(echo $RESOURCE | jq -r '.name')
            ZONE=$(echo $RESOURCE | jq -r '.zone')
            MACHINE_TYPE=$(echo $RESOURCE | jq -r '.machine_type')
            IMAGE_FAMILY=$(echo $RESOURCE | jq -r '.image_family')
            IMAGE_PROJECT=$(echo $RESOURCE | jq -r '.image_project')

            echo "Creating resource: $NAME"
            gcloud compute instances create $NAME \
              --zone=$ZONE \
              --machine-type=$MACHINE_TYPE \
              --image-family=$IMAGE_FAMILY \
              --image-project=$IMAGE_PROJECT
          done

      - name: Cleanup Resources
        if: always()  # Run cleanup even if previous steps fail
        run: |
          echo "Cleaning up resources"
          RESOURCES=$(jq -c '.resources[]' config/resources.json)
          
          for RESOURCE in $RESOURCES; do
            NAME=$(echo $RESOURCE | jq -r '.name')
            ZONE=$(echo $RESOURCE | jq -r '.zone')
            
            echo "Deleting resource: $NAME"
            gcloud compute instances delete $NAME --zone=$ZONE --quiet
          done
