name: Dev Pipeline - Test Integration

on:
  push:
    branches:
      - Dev

permissions:            # Add this section
  id-token: write        # Required for OIDC token generation
  contents: read         # Allows access to the repository contents

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev  # This specifies that the 'Dev' environment secrets will be used

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud with Workload Identity Federation
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/147961138027/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-pool"
          service_account: "github-ci-cd-dev@dev-env-441417.iam.gserviceaccount.com"

      - name: Set up gcloud CLI
        run: |
          echo "Configuring gcloud CLI"
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set compute/region europe-west4
          gcloud config set compute/zone europe-west4-a

      - name: Create VM instance for testing
        run: |
          echo "Creating a VM instance in europe-west4-a for testing integration"
          gcloud compute instances create test-instance \
            --zone=europe-west4-a \
            --machine-type=f1-micro \
            --image-family=debian-10 \
            --image-project=debian-cloud

      - name: Verify VM instance creation
        run: |
          echo "Checking if the VM instance was created"
          gcloud compute instances list --filter="name=('test-instance')"

      - name: Cleanup VM instance
        if: always()  # Run cleanup even if previous steps fail
        run: |
          echo "Deleting the test VM instance"
          gcloud compute instances delete test-instance --zone=europe-west4-a --quiet
